### ISSUE TITLE
"Run test" works, "Debug" doesn't

### ISSUE THREAD

**Issue by joshhansen** [hdevalke/rust-test-lens#17] opened 2020-02-26 08:39 UTC
When I click "Run test" I get the expected output, in this case a failing test:

```
> Executing task in folder RustTestLensBug: cargo test -- --nocapture test_something <

    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/rust_test_lens_bug-0dadc7ad428eb59d

running 1 test
thread 'test::test_something' panicked at 'Something something', src/lib.rs:5:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: std::panicking::begin_panic
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panicking.rs:404
  12: rust_test_lens_bug::test::test_something
             at src/lib.rs:5
  13: rust_test_lens_bug::test::test_something::{{closure}}
             at src/lib.rs:4
  14: core::ops::function::FnOnce::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/ops/function.rs:232
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  17: std::panicking::try
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panicking.rs:270
  18: std::panic::catch_unwind
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panic.rs:394
  19: test::run_test_in_process
             at src/libtest/lib.rs:567
  20: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:474
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test::test_something ... FAILED

failures:

failures:
    test::test_something

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
The terminal process terminated with exit code: 101

Terminal will be reused by tasks, press any key to close it.

```
But when I set a breakpoint and then click "Debug", all I get is this:

```
Launching: /home/josh/Projects/RustTestLensBug/target/debug/rust_test_lens_bug-cf2e248ae7a895f5 test_something --nocapture
Process exited with code 0.
```

The debug toolbar briefly flashes, but the breakpoint is never triggered.

Here are the versions I'm running:

```
code --version && cargo --version && rustc --version
1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
cargo 1.41.0 (626f0f40e 2019-12-03)
rustc 1.41.0 (5e1a79984 2020-01-27)
```

I'm not sure if it will reproduce for you, but I created a repository that gives this result for me:

https://github.com/joshhansen/RustTestLensBug

I also have a repository where the debug works:
https://github.com/joshhansen/RustTestLensBugNotPresent

Both repositories contain the corresponding VSCode workspace file as well. Let me know if you need anything else.

**Comment by hdevalke** [comment] 2020-02-26 19:33
Thank you for the reproducible code.
Looking at the output it mismatched the kind of the filter should have been lib and not bin.
It probably has to do with the fact that there is both a `lib` and a `main.rs` in the same crate.

```
Debugging: {
  "type": "lldb",
  "request": "launch",
  "name": "Debug test_something in lib.rs",
  "cargo": {
    "args": [
      "test",
      "--no-run",
      "--package=rust-test-lens-bug",
      "--bin=rust-test-lens-bug",
      "--manifest-path=/tmp/RustTestLensBug/Cargo.toml"
    ],
    "filter": {
      "kind": "bin"
    }
  },
  "args": [
    "test_something",
    "--nocapture"
  ],
  "cwd": "/tmp/RustTestLensBug"
}
```

**Comment by hdevalke** [comment] 2020-02-26 20:45
I identified the root cause, but it will take some time to figure out how to fix it. As a workaround, it should work if you move `src/main.rs` to `src/bin/rust-test-lens-bug.rs`.

**Comment by joshhansen** [comment] 2020-02-27 02:02
Thanks for taking a look at this so quickly! Unfortunately moving `main.rs` like you said does not seem to fix the problem. Did it work for you?

**Comment by hdevalke** [comment] 2020-02-27 06:51
It worked after reopening the project. 
But I'm afraid it requires more time to come up with a proper solution.

**Comment by joshhansen** [comment] 2020-02-27 20:16
Ah yes, it seems to work after restarting VSCode. Thanks, this is something I've been looking for for a long time!

**Comment by hdevalke** [comment] 2020-02-27 21:21
There seems to be an open discussion about using `main.rs` and `lib.rs` in the same crate: https://github.com/rust-lang/api-guidelines/issues/167

To support this, this extension should probably parse the files and build up a tree of modules/files to find out if they belong to `main.rs` or `lib.rs`. I hope at some day rls or [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/blob/fedab39011e1225b580f5afce8607c8eedad77e1/crates/rust-analyzer/src/main_loop/handlers.rs#L763) will add this functionality.

**Comment by gilescope** [comment] 2020-02-28 06:59
Would be nice to have that functionality in a separate crate- I’ve needed that before. And ideally without a dependency that builds all of cargo.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hdevalke** [comment] 2020-02-28 20:40
@gilescope any idea where to start to implement such crate?

**Comment by hdevalke** [comment] 2020-03-13 20:07
https://github.com/rust-analyzer/rust-analyzer/pull/3561 has been merged, so this feature will be available in rust-analyzer soon. I will not fix this here, as it will be too complicated.

**Closed as completed by hdevalke** 2020-03-13 20:07 UTC
